version: "3"
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: "doot"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      LOCAL_DB_CONNECTION_STRING: "Server=db;Port=5432;Database=doot;User ID=postgres;Password=postgres"
    restart: on-failure
    ports:
      - "5000:80"
      - "5001:443"

volumes:
  db_data: