version: "3.5"
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "REVERSE_PROXY"
    networks:
      - doot
    command:
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - "80:80"
  db:
    image: postgres
    container_name: "DATABASE"
    networks:
      - doot
    environment:
      POSTGRES_DB: "doot"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
      
  api:
    container_name: "API"
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - doot
    environment:
      # TODO - Use env variable      
      LOCAL_DB_CONNECTION_STRING: "Server=db;Port=5432;Database=doot;User ID=postgres;Password=${DB_PASSWORD}"
    restart: on-failure
    ports:
      - "5000:80"
      - "5001:443"
    labels:
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)"

networks:
  doot:
    name: doot_network

volumes:
  db_data: