CREATE TABLE IF NOT EXISTS todos (
     id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     title text NULL,
     description text NULL,
     completed boolean NOT NULL,
     CONSTRAINT pk_todos PRIMARY KEY (id)
    );
