using System;
using System.Reflection;
using Dapper;
using DbUp;
using Npgsql;

namespace Database
{
    internal class Migrate
    {
        private static int Main(string[] args)
        {
            // var connectionString = "Server=db;Port=5432;Database=doot;User ID=postgres;Password=postgres";
            var connectionString = "Server=db;Port=5432;Database=doot;User ID=postgres;Password=postgres";

            Console.WriteLine("Migrating Database...");

            var sql = @"CREATE TABLE IF NOT EXISTS todos (
                            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            title text NULL,
                            description text NULL,
                            completed boolean NOT NULL,
                            CONSTRAINT pk_todos PRIMARY KEY (id)
                           );";

            // using var conn = new NpgsqlConnection(connectionString);
            // conn.Execute(sql);

            var upgradeEngine = DeployChanges.To.PostgresqlDatabase(connectionString)
                .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly()).LogToConsole().Build();

            var result = upgradeEngine.PerformUpgrade();

            if (!result.Successful)
            {
                Console.Error.WriteLine("Error migrating database");
                return -1;
            }

            Console.WriteLine("Database migrated successfully.");
            return 0;
        }
    }
}